TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'll teach a move to one of your\n"
    .string "POKéMON for free.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Which POKéMON would you like me\n"
    .string "to teach a move to?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "I'll teach your POKéMON a new move\n"
    .string "right away!$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "I'll teach your POKéMON a new move\n"
    .string "right away!$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, come back anytime.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

