PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_OhPlayerWait::
    .string "MOM: Oh, {PLAYER}!\nYou're leaving?\nI have something for you.$"

PalletTown_PlayersHouse_1F_Text_GiveRunningShoesFromMom::
    .string "MOM: I've got these RUNNING SHOES\n for you!\pThey'll help you on your journey.$"

PalletTown_PlayersHouse_1F_Text_ReceivedRunningShoesFromMom::
    .string "{PLAYER} received the RUNNING SHOES\n from MOM.$"

PalletTown_PlayersHouse_1F_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n RUNNING SHOES.$"

PalletTown_PlayersHouse_1F_Text_ExplainRunningShoes::
    .string "Press the B Button to run.$"

